const actors = [
    {actor_id: 1, actor: 'Tim Robbins', birthDate: '16/10/1958', comment: 'Appeared in The Shawshank Redemption'},
    {actor_id: 2, actor: 'Marlon Brando', birthDate: '03/04/1924', comment: 'Appeared in The Godfather'},
    {actor_id: 3, actor: 'Christian Bale', birthDate: '30/01/1974', comment: 'Appeared in The Dark Knight'},
    {actor_id: 4, actor: 'Liam Neeson', birthDate: '07/06/1952', comment: 'Appeared in Schindler’s List'},
    {actor_id: 5, actor: 'John Travolta', birthDate: '18/02/1954', comment: 'Appeared in Pulp Fiction'},
    {actor_id: 6, actor: 'Viggo Mortensen', birthDate: '20/10/1958', comment: 'Appeared in The Lord of the Rings: The Return of the King'},
    {actor_id: 7, actor: 'Brad Pitt', birthDate: '18/12/1963', comment: 'Appeared in Fight Club'},
    {actor_id: 8, actor: 'Tom Hanks', birthDate: '09/07/1956', comment: 'Appeared in Forrest Gump'},
    {actor_id: 9, actor: 'Leonardo DiCaprio', birthDate: '11/11/1974', comment: 'Appeared in Inception'},
    {actor_id: 10, actor: 'Mark Hamill', birthDate: '25/09/1951', comment: 'Appeared in Star Wars: Episode V - The Empire Strikes Back'},
    {actor_id: 11, actor: 'Keanu Reeves', birthDate: '02/09/1964', comment: 'Appeared in The Matrix'},
    {actor_id: 12, actor: 'Robert De Niro', birthDate: '17/08/1943', comment: 'Appeared in Goodfellas'},
    {actor_id: 13, actor: 'Jack Nicholson', birthDate: '22/04/1937', comment: 'Appeared in One Flew Over the Cuckoo’s Nest'},
    {actor_id: 14, actor: 'Toshirō Mifune', birthDate: '01/04/1920', comment: 'Appeared in Seven Samurai'},
    {actor_id: 15, actor: 'Morgan Freeman', birthDate: '01/06/1937', comment: 'Appeared in Se7en'},
    {actor_id: 16, actor: 'Anthony Hopkins', birthDate: '31/12/1937', comment: 'Appeared in The Silence of the Lambs'},
    {actor_id: 17, actor: 'James Stewart', birthDate: '20/05/1908', comment: 'Appeared in It’s a Wonderful Life'},
    {actor_id: 18, actor: 'Tom Hanks', birthDate: '09/07/1956', comment: 'Appeared in Saving Private Ryan'},
    {actor_id: 19, actor: 'Matthew McConaughey', birthDate: '04/11/1969', comment: 'Appeared in Interstellar'},
    {actor_id: 20, actor: 'Song Kang-ho', birthDate: '17/01/1967', comment: 'Appeared in Parasite'},
    {actor_id: 21, actor: 'Michael Clarke Duncan', birthDate: '10/12/1957', comment: 'Appeared in The Green Mile'},
    {actor_id: 22, actor: 'Russell Crowe', birthDate: '07/04/1964', comment: 'Appeared in Gladiator'},
    {actor_id: 23, actor: 'Matthew Broderick', birthDate: '21/03/1962', comment: 'Appeared in The Lion King (voice of Simba)'},
    {actor_id: 24, actor: 'Leonardo DiCaprio', birthDate: '11/11/1974', comment: 'Appeared in The Departed'},
    {actor_id: 25, actor: 'Joaquin Phoenix', birthDate: '28/10/1974', comment: 'Appeared in Joker'},
    {actor_id: 26, actor: 'Kevin Spacey', birthDate: '26/07/1959', comment: 'Appeared in The Usual Suspects'},
    {actor_id: 27, actor: 'Miles Teller', birthDate: '20/02/1987', comment: 'Appeared in Whiplash'},
    {actor_id: 28, actor: 'Hugh Jackman', birthDate: '12/10/1968', comment: 'Appeared in The Prestige'},
    {actor_id: 29, actor: 'Robert Downey Jr.', birthDate: '04/04/1965', comment: 'Appeared in Avengers: Endgame'},
    {actor_id: 30, actor: 'Michael J. Fox', birthDate: '09/06/1961', comment: 'Appeared in Back to the Future'},
    {actor_id: 31, actor: 'Sigourney Weaver', birthDate: '08/10/1949', comment: 'Appeared in Alien'},
    {actor_id: 32, actor: 'Anthony Perkins', birthDate: '04/04/1932', comment: 'Appeared in Psycho'},
    {actor_id: 33, actor: 'Jack Nicholson', birthDate: '22/04/1937', comment: 'Appeared in The Shining'},
    {actor_id: 34, actor: 'Jamie Foxx', birthDate: '13/12/1967', comment: 'Appeared in Django Unchained'},
    {actor_id: 35, actor: 'Ryan Gosling', birthDate: '12/11/1980', comment: 'Appeared in Blade Runner 2049'},
    {actor_id: 36, actor: 'Leonardo DiCaprio', birthDate: '11/11/1974', comment: 'Appeared in The Wolf of Wall Street'},
    {actor_id: 37, actor: 'Ryan Gosling', birthDate: '12/11/1980', comment: 'Appeared in La La Land'},
    {actor_id: 38, actor: 'Tom Hardy', birthDate: '15/09/1977', comment: 'Appeared in Mad Max: Fury Road'},
    {actor_id: 39, actor: 'Jim Carrey', birthDate: '17/01/1962', comment: 'Appeared in The Truman Show'},
    {actor_id: 40, actor: 'Tom Hanks', birthDate: '09/07/1956', comment: 'Appeared in Toy Story (voice of Woody)'},
    {actor_id: 41, actor: 'Russell Crowe', birthDate: '07/04/1964', comment: 'Appeared in A Beautiful Mind'},
    {actor_id: 42, actor: 'Ralph Fiennes', birthDate: '22/12/1962', comment: 'Appeared in The Grand Budapest Hotel'},
    {actor_id: 43, actor: 'Joaquin Phoenix', birthDate: '28/10/1974', comment: 'Appeared in Her'},
    {actor_id: 44, actor: 'Amy Poehler', birthDate: '16/09/1971', comment: 'Appeared in Inside Out (voice of Joy)'},
    {actor_id: 45, actor: 'Jeff Bridges', birthDate: '04/12/1949', comment: 'Appeared in The Big Lebowski'},
    {actor_id: 46, actor: 'Chadwick Boseman', birthDate: '29/11/1976', comment: 'Appeared in Black Panther'},
    {actor_id: 47, actor: 'Shameik Moore', birthDate: '04/05/1995', comment: 'Appeared in Spider-Man: Into the Spider-Verse (voice of Miles Morales)'},
    {actor_id: 48, actor: 'Chris Pratt', birthDate: '21/06/1979', comment: 'Appeared in Guardians of the Galaxy'},
    {actor_id: 49, actor: 'Daniel Kaluuya', birthDate: '24/02/1989', comment: 'Appeared in Get Out'},
    {actor_id: 50, actor: 'Jesse Eisenberg', birthDate: '05/10/1983', comment: 'Appeared in The Social Network'}
  ];
module.exports = { actors }